package dev.user;

public enum SecurityQuestion {
    WHAT_IS_YOUR_MOTHERS_MAIDEN_NAME,
    WHAT_WAS_THE_NAME_OF_YOUR_FIRST_PET,
    WHAT_IS_YOUR_FAVORITE_MOVIE,
    IN_WHAT_CITY_WERE_YOU_BORN,
    WHAT_WAS_THE_MAKE_AND_MODEL_OF_YOUR_FIRST_CAR,
    WHAT_IS_YOUR_FAVORITE_BOOK,
    WHAT_IS_THE_NAME_OF_YOUR_BEST_CHILDHOOD_FRIEND,
    WHAT_IS_YOUR_FAVORITE_VACATION_SPOT,
    WHAT_IS_THE_NAME_OF_YOUR_FAVORITE_TEACHER,
    WHAT_WAS_THE_NAME_OF_YOUR_FIRST_SCHOOL;
}
